### ISSUE TITLE
Karma exclude key is ignored

### ISSUE THREAD

**Issue by mikehaas763** [rolaveric/karma-systemjs#20]
For context, I am currently using this adapter with the output from a build process. So I'm not having this plugin or SystemJS transpile my code. It's already done as a part of my build process. The build process puts everything into a www/ directory.

So I set up my files key to be `'www/**/*.js'`. There is a subdirectory in www/ named lib/ that contains my bower dependencies. So of course any test file that matches the default test file extensions is ran and will likely always fail.

I assumed putting an entry of 'www/lib' in the karma exclude key would cause the lib/ files to be ignored but I see no difference after. It is still trying to run the deps test files.

I'm willing to invest some time into this plugin not only because I want to but because I need this tool for my job. Is it just a matter of putting some condition that ignores files in the karma exclude key?

**Comment by rolaveric** [comment]
I'm actually surprised that `exclude` doesn't work as is.  It must be getting run after the plugin frameworks startup because at that point `files` is still a set of patterns - it wouldn't have been resolved yet.
I'll take a closer look tonight.

Worst case scenario, I'll have to put some additional logic into how test suites are chosen.
At the moment the adapter looks at the list of file names karma serves, and looks for any that match a regular expression.
Perhaps I need to use globs and have it resolve `excludes` as well... but that should've already happened before the adapter starts :/

**Comment by mikehaas763** [comment]
@rolaveric I also assumed that 'exclude' would have already been resolved by karma before this adapter is run. For science, I tested **not** using the systemjs.files[] property and just used the karma files:[] directly like so `files: [{pattern: 'www/**/*.js', included: false}]`

**Comment by mikehaas763** [comment]
Ah, I found a way to make it work. I had tried this earlier but I must have had more than one thing wrong at that point because it didn't work.

Using `exclude: ['www/lib/**/*']` works. I'm not sure why karma (or the underlying minimatch) does not match an explicit directory like I had before. Maybe something that should be brought up with the karma team?

**Comment by rolaveric** [comment]
Yeah I'd say raise it with Karma, though it'll probably come down to what glob engine they use in `exclude`.

**Comment by mikehaas763** [comment]
Ok will do.
