### ISSUE TITLE
karma-systemjs breaks with systemjs / es6-module-loader 0.17

### ISSUE THREAD

**Issue by msegado** [rolaveric/karma-systemjs#23]
Karma-systemjs seems to be broken with systemjs and es6-module-loader 0.17, which are the versions you currently get with `npm install systemjs es6-module-loader`. The specific errors I ran into were (1) System.config not being defined as a function, and (2) Promise not being available [at least in PhantomJS].

I didn't troubleshoot too much, but I can confirm that these issues aren't present when manually using the latest 0.16.x of systemjs / es6-module-loader instead if that helps!

(Thanks for this project, by the way)

**Comment by rolaveric** [comment]
Thanks for the heads up.
Looks like there's a few breaking changes in 0.17 I'll need to account for:
https://github.com/systemjs/systemjs/releases/tag/0.17.0
Lots of shiny new features too (Thanks @guybedford + contributors!)

The missing Promise issue should be solvable by including `system-polyfills.js`.
I'll review how karma-systemjs handles `es6-module-loader` (I don't think it checks the SystemJS config for a `paths['es6-module-loader']`) and make sure it now does the same for `system-polyfills`.

Not sure about the 'System.config' undefined issue though.
Could be the `System.baseURL = ...` setting in `adapter.js` - I'll dig into it once I get home.

Will also need to check `System.defaultJSExtensions` to disable the `.js` extension handling going on.

(Much appreciated :smiley: )

**Comment by rolaveric** [comment]
Should be fixed with b118c7c117460adce48297bfebf34d38ddd9b53c - published as 0.5.0

The `require.resolve()` path for SystemJS had changed slightly with 0.17.0, which is why you were getting "System.config is undefined" errors.
I recommend adding a `systemjs` entry to the `paths` in your SystemJS config (A little recursive, I know) so it doesn't affect you in the future.  In fact I'm going to deprecate the `require.resolve()` lookups with #24 

It now adds `system-polyfills.js` to the list of files just before SystemJS.
Looked up as `system-polyfills` in SystemJS config.

Also the `.js` extension is left alone for module names, unless `System.defaultJSExtensions = true`.

Should solve all your issues.  Let me know if you still have any problems.

**Comment by rolaveric** [comment]
I'm going to assume all is well - closing.

**Comment by msegado** [comment]
Whoops, sorry for the lack of followup @rolaveric - yes, I can confirm that this works now.
