### ISSUE TITLE
Tests not transpiled with babel

### ISSUE THREAD

**Issue by mikehaas763** [rolaveric/karma-systemjs#48]
I have set `transpiler: 'babel'` in my karma config file under systemjs.config. When I start karma and run my tests with Chrome, they run and the tests pass. I assume that's because Chrome has supported some ES6 features. Arrow functions being the only ES6 feature I'm using in my one sample testSpec.js file. However when I switch to PhantomJS I assume that the files aren't being transpiled. I get the error:

![image](https://cloud.githubusercontent.com/assets/2096573/10046690/53ca4c06-61d8-11e5-908c-0f1803bc7c42.png)

How can I get more debugging information or why might the transpiling not actually be happening?

**Comment by dmackerman** [comment]
You may need a shim for PhantomJS. I believe we did. Try this one: https://www.npmjs.com/package/karma-es6-shim

**Comment by rolaveric** [comment]
The fact that it says "Parse error" does suggest that PhantomJS has been passed raw ES6 code, that it just can't parse.
If it was a "X is null or undefined" error, then I'd be looking at missing polyfills, like if you don't have `import 'babel/polyfill';` declared anywhere.
One place to start might be to bump up the `logLevel` in the karma config to debug: http://karma-runner.github.io/0.13/config/configuration-file.html
I suspect what's happening is Karma is including your files directly (ie. Like script tags in the HTML) rather than just serving them and letting SystemJS import them.

Also @dmackerman - In this case it would be `frameworks: ['systemjs', 'jasmine', 'es6-shim']` :P

**Comment by mikehaas763** [comment]
When I was running the exact same config but with Chrome it was serving the files through System and not just injecting script references. Hopefully I can get a chance to verify that soon.

**Comment by rolaveric** [comment]
Hey @mikehaas763, are you still having this issue?

**Comment by mikehaas763** [comment]
@rolaveric I'm not working with the project that this applied to any more, so I'm not using this anymore.
