### ISSUE TITLE
Imports need to be sequential

### ISSUE THREAD

**Issue by jedvardsson** [rolaveric/karma-systemjs#77]
You need to maintain the import order when calling System.import. http://karma-runner.github.io/0.13/config/files.html buy chaining the promises and not concatenate them into an array. For example, I get a problem when loading angular and angular-mocks, where angular-mocks sometimes loads faster than angular thus failing.

Another problem is that when systemjs fails to import a module, the error message is not very helpful. Is it possible to improve this?

**Comment by rolaveric** [comment]
Hmmm, that's an interesting one.
You're right, the sequence is not guaranteed with `Promise.all([System.import(), ...])`.
I personally have never run across this issue because I only import test suites, and then those test suites declare `import 'angular'; import 'angular-mocks';`, which does guarantee sequence.

I was hesitant to chain the promises to guarantee sequence because it could slow things down. Especially in situations where the Karma and the browser aren't on the same machine (eg. Using SauceLabs or a separate Selenium server).
But I see [`karma-jspm`](https://github.com/Workiva/karma-jspm) do [exactly as you describe](https://github.com/Workiva/karma-jspm/blob/master/src/adapter.js#L50).
So what I'll do is put a configuration switch around it so you get the best of both worlds. If `strictImportSequence` is true, the import promises will get chained.

What are you currently seeing when SystemJS fails to import?
My most common error from importing is a 404 because I haven't added the file to the Karma config, so I see the 404 output from the Karma server. If you've got another example I can see what I can do.

**Comment by rolaveric** [comment]
Fixed by 611741913daaaf8dd887e34445bc51aec88a7728

**Comment by VivekPMenon** [comment]
Looks like this change is not yet published to npm repo??? 

**npm i karma-systemjs** didn't bring these changes (was checking adapter file)

But **npm i git+https://github.com/rolaveric/karma-systemjs.git --save-dev** did the job.

**Comment by rolaveric** [comment]
Sorry about that, I've been preoccupied with a newborn.
Thanks for picking up on that bug - fixed now by 92dd9b8514fe4c0d7725decee24e6846e7e85481
Published changes as 0.14.0 to npm.

**Comment by VivekPMenon** [comment]
Thanks much and congratulation :-)
