### ISSUE TITLE
Question: Should karma-systemjs work with jspm installed dependencies?

### ISSUE THREAD

**Issue by twalker** [rolaveric/karma-systemjs#8]
Thanks so much for this karma plugin.

I'm trying to use it in a project where I use the `jspm` instead of `bower` for installing dependencies.
It may be a misconfiguration on my part (I'm new to karma), but I'm having path issues between the SystemJS `baseURL` and the Karma `basePath`:

I receive the error, with a hint that my baseURL needed adjusted:

```
TypeError: Illegal module name "/base/app/search.controller.spec"
  Hint: Is the working directory different when you run karma?
  You may need to change the baseURL of your SystemJS config inside your karma config.
  It's currently checking "/base/../public/js/"
  Note: "/base/" is where karma serves files from.
```

If I adjust the `baseURL` for in the karma.config, paths to `jspm_packages` are incorrect. 

My specific issue aside, have you tried using `karma-systemjs` with jspm installed dependencies?

**Comment by rolaveric** [comment]
I haven't personally tried using JSPM, but I don't think your issue is specific to JSPM - you'd have just as much trouble if you were using bower.
I think it's the relative "baseURL" that it doesn't like.

To give some background - The adapter (ie. What runs inside the browser) of karma-systemjs works by taking the list of files that karma serves (`window.__karma__.files`), works out which of those are test suites, and then tries to translate those file paths into modules that it can call `System.import()` with.
One part of that translation process is to trim "/base" + the SystemJS "baseURL" from the start of the file path.
It's failed to do that in this situation (Easy to tell cause the module name it tried starts with "/base") because your BaseURL doesn't match the file paths it's serving.

Changing your "baseURL" to "/" or "/app/" doesn't work because you already have import paths somewhere which depend upon that "baseURL" (eg. The "jspm_packages" paths).
I think that gives you 2 options:
1. Change "baseURL" to not require a "../" and change your import paths to work with it.
2. Create a customised SystemJS configuration inside your karma config that changes the "baseURL", and uses "paths" and/or "maps" to map your import paths correctly.

I'd personally go with option 1 and set SystemJS "paths" for all your "jspm_packages".  That gives you some flexibility if you ever wanted to use a CDN or support including multiple versions at once - you just switch out the path in the one place.

**Comment by twalker** [comment]
Thanks for the background and suggestions. I'll go with your first suggestion. I believe part of my issue was having `karma.conf.js` in a different directory from SystemJS's `config.js`.

I recommend trying out [jspm](http://jspm.io/) when you have the time/interest.

Thanks again.

**Comment by rolaveric** [comment]
Happy to help.

Just one last thing - it's not so much about where the config files are stored, but about where your http-server runs compared to karma.
Think of it like running the same code on 2 different domains.  What does "/" (absolute root) mean in each context?
What does "baseURL" need to be, relative to "/", to include everything you need in the browser?

I've looked into jspm, and actually found SystemJS initially after seeing [Glen Maddern's post](http://glenmaddern.com/articles/javascript-in-2015) about it.
Trouble is that I've got existing projects and infrastructure that uses npm and bower. Maybe switching them over to jspm wouldn't be that hard, but I don't have the motivation just yet :)
