### ISSUE TITLE
How does Karma config section for systemjs overlay/interract with the systemjs.config file used for loading an app?

### ISSUE THREAD

**Issue by kburson** [rolaveric/karma-systemjs#9]
Can you help me understand how the `karma.con.jsf:: systemjs` object relates to the `system.config.js::System.config({})` object ?  
The karma.config::system.js object references the system.config.js file:

**karma.config.js**
```
module.exports = function (config) {
    basePath: projectRoot,
    urlRoot: '',
    hostname: 'localhost',
    frameworks: [ ...],
    plugins: [...],
    files: [],
    systemjs: {                             // <---
        configFile: 'system.config.js',     // <---
        files: [...  ],
        config: {
            transpiler: 'traceur',
            baseUrl: '/',
            paths: {                          // <---
                'asset':  'location'          // <---
                ...
            }
        }
        testFileSuffix: '.spec.js'
    },
    preprocessors: { ... },
    reporters: [...],
    browsers: [...]
    port: 9876,
    runnerPort: 9100
}
```

**system.config.js**
```
System.config({
    baseURL: '/', //relative to index.html location
    paths: {                                 // <---
         'asset':  'location'               // <---
    },
    meta: { ... },
    map: { ... }
});
```

They both have `baseUrl` and `paths` objects for denoting location of dependencies.  Does the karma config object override the system.config.js settings?

I have configured the system.config.js to locate my dependencies within a deployable build folder.

I would like to have the karma systemjs settings look for those same dependencies in their 'natural habitat' whether that be bower_components or node_modules.  This way the unit/integration tests can run against the raw source files, while the e2e and manual testing would run against the pre-compiled app in the build folder.  This would be ideal.  Is this possible?

Lastly, if you have time, I would welcome a discussion about project structures and efficiency.  I am trying to find a structure that will work well for today and migrate easily for tomorrow (When ES6 and Angular 2.0 are mainstream).

Thanks,

Kendrick

**Comment by rolaveric** [comment]
Values are merged 'from' the config defined in "systemjs.configFile" (ie. system.config.js) into the config defined in "systemjs.config".
Any properties that already exist in "systemjs.config" are maintained.
"paths", "map", and "meta" go through the same process.

You can see the code here - it's pretty simple:
https://github.com/rolaveric/karma-systemjs/blob/master/lib/index.js#L46-L62

So what you're asking for is definitely possible - I reuse the same "system.config.js" for dev, testing, and bundling.  I only make minor tweaks for testing (eg. Include angular-mocks) and bundling (eg. Set baseURL to './', since it's looking at the file system).

As for project structure... my advice would be to leverage SystemJS as much as possible.
For instance, I used to use the 'gulp-angular-templatecache' plugin to read my HTML templates and load them into an angular module that then loads them into $templateCache.
Now I just use the 'text' plugin for SystemJS, and pass that variable directly to 'template' rather than 'templateUrl' in my routes and directives.
Take that, plus built in minification and sourcemaps: I've just killed off something like 5 gulp plugins that I would have had to pipe together.
In this case I'm also only including what I KNOW is being used.

**Comment by kburson** [comment]
Ok, so `system.config.js` is merged with `karma.conf.js::systemjs{}`, with the settings in `system.config.js` taking precedence (overwriting any identical settings in `karma.conf.js`).

With this then how do you run the tests in a different layout than their native runtime?
What I mean is; 

1) for dev time I want to run tests against the pre-compiled src files accessing the library dependencies directly from `node_modules` and `bower_components`.  

2) For localhost server and e2e tests I want to host the compiled app in a build folder with all assets and dependencies collected locally, hence systemjs would be looking in the local `/js/lib` folder, not in the `bower_components` or `npm_modules` folders.

3) For production I want a deployable asset, either a zip of the minified build folder, or a minified bundle of all assets in the build folder.  The paths would probably be similar to the locahost folder, only referenced as such from within the bundle.

In each of the 3 cases the location of the assets and dependencies changes (btw 2 & 3 the change is from loose-leaf to minified bundle).  The Biggest difference is having Karma-systemjs pre-compile all my source files, along with tests, and execute the tests from memory rather than having to compile them to disk and then load them back in from disk.

I am getting confused on the precedence of the various path settings:

* basePath
* baseURL
* urlRoot

It seems that if I want to import my modules without using long relative paths: i.e. 
 
```import app from '../../../app.module'```

rather than

```import app from 'client/src/app/modules/app.module'```

I need to have a root that I can start from that is common in all 3 environments (test, build, prod).  I was trying to use the `client/src/modules` folder for this.  With this I can have a nested controller or directive that depends on something in a cousin folder, by starting the path at `modules` I can walk in from there, and if the path is relative local just use the import `./folder/file`  import format.

**Comment by rolaveric** [comment]
_with the settings in system.config.js taking precedence_

No, it's the reverse.  `system.config.js` properties are only copied into `karma.conf.js:systemjs.config` if that property does not already exist.

_I am getting confused on the precedence of the various path settings:_

If I'm reading the [Karma source code](https://github.com/karma-runner/karma/blob/master/lib/middleware/karma.js) correctly, the `basePath` is where the HTTP server sets it's `base/` folder from.  And if you try to include a file which isn't inside that folder (eg. `../someFile.js`), it goes under `absolute/`.

`baseURL` is what SystemJS uses for all module names that aren't: a) Already found in `map` or `paths` in `system.config.js`, or b) Start with `./` or `../` which are relative to the current module.

`urlRoot` lets you change the root path for Karma in the browser. eg. You could set it to "/karma/" and you'd find your files under "/karma/base/".
It's only useful in very specific circumstances. I'd leave it as "/".

_I need to have a root that I can start from that is common in all 3 environments..._

Well under normal circumstances, you're going to need to reference 3 types of modules: source code, unit tests, and third-party libraries.
So your `baseURL` needs to encompass all 3 of these _unless_ you reference them in the `map` or `paths` of your `system.config.js` with absolute paths.
eg. You may use `map` for third-party libraries because you expect to use a CDN, or just don't want to write `import 'node_modules/lodash/lodash.js'` 500 times.

I tend to stick to "/" for the `baseURL`, change the `System.import(mainModule)` according to the environment, use relative module names (ie. Start with `./` or `../`) for everything that's going to stay in the same relative structure, and use `map` for everything else (eg. third party libraries, files created at build time, etc.).

**Comment by newduke** [comment]
@rolaveric I have found another issue with the merge behavior of dependencies.  This is a snippet from our karma `config.systemjs.config`
```javascript
                meta: {
                    // HACK: should be:
                    // 'ud.videojs-ready': { deps: [] }
                    // but the merge function is treating deps as an object and merging the
                    // dependencies instead of clobbering
                    'ud.videojs-ready': { deps: "angular" }
                }
```

**Comment by rolaveric** [comment]
@newduke Hmmm, I'm not sure what's the best solution for that.
I suppose we normally want to merge objects - adding or overwriting property values.
Arrays are few and far between.  According to [SystemJS docs](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md), only `bundles`, `depCache`, and `meta.deps`.
So it should be fair to say that objects are merged and arrays get clobbered, so something like this for [Line 153](https://github.com/rolaveric/karma-systemjs/blob/master/lib/framework.js#L153):
```js
_.merge(kConfig, kSystemjsConfig.config, function(objectValue, sourceValue) {
  if (_.isArray(sourceValue)) {
    return sourceValue;
  }
});
```
Does that work for you?

**Comment by newduke** [comment]
@rolaveric That works for me.  Thanks for the fix!

**Comment by rolaveric** [comment]
Don't thank me yet - I still need to implement it.
